services:
  smart-bot:
    build: 
      context: ../../
      dockerfile: docker/remote/Dockerfile
    depends_on:
      - 'chroma'
      - 'ollama'
    env_file: ../../.env
    networks:
      - smart_bot_network
    environment:
      - PYTHONPATH=/workspaces/Smart_Bot
      - CHROMA_HOST=chroma
      - OLLAMA_API_HOST=ollama
      - LLM_MODEL=codellama


  ollama:
    restart: unless-stopped
    image: ollama/ollama:latest
    volumes:
      - ollama-storage:/root/.ollama
    networks:
      - smart_bot_network


  chroma:
    restart: unless-stopped
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma-storage:/index_data
    networks:
      - smart_bot_network


volumes:
  ollama-storage:
  chroma-storage:

networks:
  smart_bot_network:
    name: smart_bot_network
