version: '3.8'

services:
  smart_bot:
    container_name: smart_bot
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/Smart_Bot:cached
    command: sleep infinity
    depends_on:
      - ollama
      - chroma
    networks:
      - smart_bot_network
    environment:
      - PYTHONPATH=/workspaces/Smart_Bot
      - CHROMA_HOST=chroma
      - OLLAMA_API_HOST=http://ollama:11434
      - LLM_MODEL=codellama

  ollama:
    container_name: ollama
    restart: unless-stopped
    image: ollama/ollama:latest
    volumes:
      - ollama-storage:/root/.ollama
    networks:
      - smart_bot_network


  chroma:
    container_name: chroma
    restart: unless-stopped
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma-storage:/index_data
    networks:
      - smart_bot_network


volumes:
  ollama-storage:
  chroma-storage:

networks:
  smart_bot_network:
    name: smart_bot_network
